{
	"IsEnabled": true,
	"Name": "EditorHelper2",
	"Version": "1.0.4.5",
	"Assemblies":
	[
		{
			"Path": "/UnturnedUITools/Bin/UnturnedUITools.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/Microsoft.Extensions.Logging.Abstractions.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/Microsoft.Extensions.Configuration.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/Microsoft.Extensions.Configuration.Abstractions.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/Microsoft.Extensions.Primitives.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/System.Security.Cryptography.Xml.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/System.Security.Cryptography.Cng.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/System.Security.Cryptography.Pkcs.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/System.Security.AccessControl.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/System.Formats.Asn1.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/dnlib.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/EPPlus.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/EPPlus.Interfaces.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/Microsoft.IO.RecyclableMemoryStream.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/System.ComponentModel.Annotations.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/DiscordGameSDK.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/0Harmony.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/Publicizer.dll",
			"Role": "Client"
		},
		{
			"Path": "/Libraries/EditorHelper2.common.dll",
			"Role": "Client"
		},
		{
			"Path": "/EditorHelper2.dll",
			"Role": "Client"
		}
	]
}