<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <Version>1.0.4.8</Version>
        <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    </PropertyGroup>

    <!-- Publicizer -->
    <ItemGroup>
        <Publicize Include="Assembly-CSharp" MemberPattern="^SDG\.(Unturned|Framework)\.(Asset|TerrainTileLayer|Player|Editor|LocationDevkitNodeSystem|Level|LevelObjects|RuntimeGizmos|Road|Foliage|ReunObjectRemove|Menu|ItemStore|EditorInteract|GlazierResources|Utilities.TimeUtility|CullingVolume|TerrainEditor).*" />
    </ItemGroup>
    
    <!-- Analyzer -->
    <ItemGroup>
        <Analyzer Include="..\Libs\EditorHelperAnalyzers.dll" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="HighlightingSystem">
        <HintPath>..\Libs\HighlightingSystem.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AssetsTools.NET" Version="3.0.4" />
      <PackageReference Include="DanielWillett.UnturnedUITools" Version="1.4.7" />
      <PackageReference Include="EditorHelper.Unturned.Client" Version="3.26.3.8" />
      <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Lib.Harmony" Version="2.3.6" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Extensions\Spawns\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\EditorHelper2.common\EditorHelper2.common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Features\ReferenceOverlay\ReferenceOverlayMeshBuilder.cs" />
      <Compile Remove="Features\ReferenceOverlay\ReferenceOverlaySettings.cs" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="xcopy &quot;$(TargetPath)&quot; &quot;$(SolutionDir)Module\&quot; /Y /I" />
    </Target>

</Project>
