<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
        <Version>1.0.4.2</Version>
    </PropertyGroup>

    <!-- Publicizer -->
    <ItemGroup>
        <Publicize Include="Assembly-CSharp" MemberPattern="^SDG\.(Unturned|Framework)\.(Asset|UseableGun|Player|Editor|LocationDevkitNodeSystem|Level|LevelObjects|RuntimeGizmos|Road|Foliage|ReunObjectRemove|Menu|ItemStore|EditorInteract|GlazierResources|Utilities.TimeUtility|CullingVolume).*" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="EPPlus" Version="8.4.1" />
      <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4-beta1" />
      <PackageReference Include="RocketModFix.UnityEngine.Redist" Version="2022.3.62.3" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\Unturned\Unturned_Data\Managed\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="com.rlabrecque.steamworks.net">
        <HintPath>..\Libs\com.rlabrecque.steamworks.net.dll</HintPath>
      </Reference>
      <Reference Include="DiscordGameSDK">
        <HintPath>..\Libs\DiscordGameSDK.dll</HintPath>
      </Reference>
      <Reference Include="HighlightingSystem">
        <HintPath>..\Libs\HighlightingSystem.dll</HintPath>
      </Reference>
      <Reference Include="SDG.Glazier.Runtime">
        <HintPath>..\Libs\SDG.Glazier.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="SDG.NetPak.Runtime">
        <HintPath>..\Libs\SDG.NetPak.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="SDG.NetTransport">
        <HintPath>..\Libs\SDG.NetTransport.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Burst">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\Unity.Burst.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Burst.Unsafe">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\Unity.Burst.Unsafe.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Collections">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\Unity.Collections.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Collections.LowLevel.ILSupport">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\Unity.Collections.LowLevel.ILSupport.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Mathematics">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\Unity.Mathematics.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Postprocessing.Runtime">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\Unity.Postprocessing.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.TextMeshPro">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\Unity.TextMeshPro.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AccessibilityModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.AccessibilityModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AIModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.AIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AndroidJNIModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.AndroidJNIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AnimationModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ARModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.ARModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AssetBundleModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AudioModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ClothModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.ClothModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ClusterInputModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.ClusterInputModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ClusterRendererModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.ClusterRendererModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ContentLoadModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.ContentLoadModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CrashReportingModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.CrashReportingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.DirectorModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.DirectorModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.DSPGraphModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.DSPGraphModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.GameCenterModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.GameCenterModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.GIModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.GIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.GridModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.GridModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.HotReloadModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.HotReloadModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ImageConversionModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.IMGUIModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.InputLegacyModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.InputModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.InputModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.JSONSerializeModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.LocalizationModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.LocalizationModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.NVIDIAModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.NVIDIAModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ParticleSystemModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.PerformanceReportingModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.PerformanceReportingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.Physics2DModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.PhysicsModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ProfilerModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.ProfilerModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.PropertiesModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.PropertiesModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ScreenCaptureModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.ScreenCaptureModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SharedInternalsModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.SharedInternalsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SpriteMaskModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.SpriteMaskModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SpriteShapeModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.SpriteShapeModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.StreamingModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.StreamingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SubstanceModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.SubstanceModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SubsystemsModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.SubsystemsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TerrainModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.TerrainModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TerrainPhysicsModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.TerrainPhysicsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextCoreFontEngineModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextCoreTextEngineModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextRenderingModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TilemapModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.TilemapModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TLSModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.TLSModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIElementsModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UIElementsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UmbraModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UmbraModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityAnalyticsModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UnityAnalyticsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityConnectModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UnityConnectModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityCurlModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UnityCurlModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityTestProtocolModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UnityTestProtocolModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestAudioModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestTextureModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestWWWModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VehiclesModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.VehiclesModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VFXModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.VFXModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VideoModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.VideoModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VirtualTexturingModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.VirtualTexturingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VRModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.VRModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.WindModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.WindModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.XRModule">
        <HintPath>..\..\..\..\SteamLibrary\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.XRModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEx">
        <HintPath>..\Libs\UnityEx.dll</HintPath>
      </Reference>
      <Reference Include="UnturnedDat">
        <HintPath>..\Libs\UnturnedDat.dll</HintPath>
      </Reference>
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="xcopy &quot;$(TargetPath)&quot; &quot;$(SolutionDir)Module\Libraries&quot; /Y /I" />
    </Target>

</Project>
