<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
        <Version>1.0.4.6</Version>
    </PropertyGroup>

    <!-- Publicizer -->
    <ItemGroup>
        <Publicize Include="Assembly-CSharp" MemberPattern="^SDG\.(Unturned|Framework)\.(Asset|UseableGun|Player|Editor|LocationDevkitNodeSystem|Level|LevelObjects|RuntimeGizmos|Road|Foliage|ReunObjectRemove|Menu|ItemStore|EditorInteract|GlazierResources|Utilities.TimeUtility|CullingVolume|GlazierProxy_|ISleekProxyImplementation).*" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AssetsTools.NET" Version="3.0.4" />
      <PackageReference Include="EditorHelper.Unturned.Client" Version="3.26.3.3" />
      <PackageReference Include="EPPlus" Version="8.4.1" />
      <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4-beta1" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="DiscordGameSDK">
        <HintPath>..\Libs\DiscordGameSDK.dll</HintPath>
      </Reference>
      <Reference Include="HighlightingSystem">
        <HintPath>..\Libs\HighlightingSystem.dll</HintPath>
      </Reference>
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="xcopy &quot;$(TargetPath)&quot; &quot;$(SolutionDir)Module\Libraries&quot; /Y /I" />
    </Target>

</Project>
